// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axwmvvwmhbmzmamcwbqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4d212dndtaGJtem1hbWN3YnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNjgzNzIsImV4cCI6MjA4NTY0NDM3Mn0.7NqtmF2Q3O7aC58fYHvKpxwc11bFVV2VNPM_FCcL8Sw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});